// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'editor.dart';
import 'frb_generated.dart';
import 'highlighter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vim_engine.dart';

Future<String> helloFromRust() => RustLib.instance.api.crateApiHelloFromRust();

Future<TypstCompileResult> compileTypst({
  required String content,
  required List<ExtraFile> extraFiles,
}) => RustLib.instance.api.crateApiCompileTypst(
  content: content,
  extraFiles: extraFiles,
);

Future<Uint8List?> compilePdf({
  required String content,
  required List<ExtraFile> extraFiles,
}) => RustLib.instance.api.crateApiCompilePdf(
  content: content,
  extraFiles: extraFiles,
);

EditorView getEditorView({
  required BigInt startLine,
  required BigInt endLine,
}) => RustLib.instance.api.crateApiGetEditorView(
  startLine: startLine,
  endLine: endLine,
);

VimAction? handleEditorKey({required String key}) =>
    RustLib.instance.api.crateApiHandleEditorKey(key: key);

Future<void> handleEditorTriggerHighlight() =>
    RustLib.instance.api.crateApiHandleEditorTriggerHighlight();

void handleEditorReplaceRange({
  required BigInt startU16,
  required BigInt endU16,
  required String text,
  BigInt? cursorU16,
}) => RustLib.instance.api.crateApiHandleEditorReplaceRange(
  startU16: startU16,
  endU16: endU16,
  text: text,
  cursorU16: cursorU16,
);

void handleEditorUpdateSelection({required BigInt cursorU16}) => RustLib
    .instance
    .api
    .crateApiHandleEditorUpdateSelection(cursorU16: cursorU16);

String getEditorContent() => RustLib.instance.api.crateApiGetEditorContent();

void setEditorContent({required String content}) =>
    RustLib.instance.api.crateApiSetEditorContent(content: content);

class ExtraFile {
  final String name;
  final Uint8List data;

  const ExtraFile({required this.name, required this.data});

  @override
  int get hashCode => name.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtraFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          data == other.data;
}

class TypstCompileResult {
  final List<TypstPage> pages;
  final List<TypstError> errors;

  const TypstCompileResult({required this.pages, required this.errors});

  @override
  int get hashCode => pages.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstCompileResult &&
          runtimeType == other.runtimeType &&
          pages == other.pages &&
          errors == other.errors;
}

class TypstError {
  final String message;
  final int line;
  final int column;

  const TypstError({
    required this.message,
    required this.line,
    required this.column,
  });

  @override
  int get hashCode => message.hashCode ^ line.hashCode ^ column.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          line == other.line &&
          column == other.column;
}

class TypstPage {
  final Uint8List image;

  const TypstPage({required this.image});

  @override
  int get hashCode => image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstPage &&
          runtimeType == other.runtimeType &&
          image == other.image;
}
