// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'highlighter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vim_engine.dart';

class EditorView {
  final List<RenderLine> lines;
  final BigInt cursorLine;
  final BigInt cursorColumnU16;
  final BigInt cursorGlobalU16;
  final VimMode mode;

  const EditorView({
    required this.lines,
    required this.cursorLine,
    required this.cursorColumnU16,
    required this.cursorGlobalU16,
    required this.mode,
  });

  @override
  int get hashCode =>
      lines.hashCode ^
      cursorLine.hashCode ^
      cursorColumnU16.hashCode ^
      cursorGlobalU16.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorView &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          cursorLine == other.cursorLine &&
          cursorColumnU16 == other.cursorColumnU16 &&
          cursorGlobalU16 == other.cursorGlobalU16 &&
          mode == other.mode;
}

class RenderLine {
  final String text;
  final List<HighlightSpan> spans;
  final bool isComposing;
  final BigInt startU16;

  const RenderLine({
    required this.text,
    required this.spans,
    required this.isComposing,
    required this.startU16,
  });

  @override
  int get hashCode =>
      text.hashCode ^ spans.hashCode ^ isComposing.hashCode ^ startU16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          spans == other.spans &&
          isComposing == other.isComposing &&
          startU16 == other.startU16;
}
