// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'editor.dart';
import 'frb_generated.dart';
import 'highlighter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'vim_engine.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  VimAction dco_decode_box_autoadd_vim_action(dynamic raw);

  @protected
  VimRange dco_decode_box_autoadd_vim_range(dynamic raw);

  @protected
  EditorView dco_decode_editor_view(dynamic raw);

  @protected
  ExtraFile dco_decode_extra_file(dynamic raw);

  @protected
  HighlightSpan dco_decode_highlight_span(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ExtraFile> dco_decode_list_extra_file(dynamic raw);

  @protected
  List<HighlightSpan> dco_decode_list_highlight_span(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RenderLine> dco_decode_list_render_line(dynamic raw);

  @protected
  List<TypstError> dco_decode_list_typst_error(dynamic raw);

  @protected
  List<TypstPage> dco_decode_list_typst_page(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  VimAction? dco_decode_opt_box_autoadd_vim_action(dynamic raw);

  @protected
  VimRange? dco_decode_opt_box_autoadd_vim_range(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  RenderLine dco_decode_render_line(dynamic raw);

  @protected
  TypstCompileResult dco_decode_typst_compile_result(dynamic raw);

  @protected
  TypstError dco_decode_typst_error(dynamic raw);

  @protected
  TypstPage dco_decode_typst_page(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VimAction dco_decode_vim_action(dynamic raw);

  @protected
  VimMode dco_decode_vim_mode(dynamic raw);

  @protected
  VimRange dco_decode_vim_range(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VimAction sse_decode_box_autoadd_vim_action(SseDeserializer deserializer);

  @protected
  VimRange sse_decode_box_autoadd_vim_range(SseDeserializer deserializer);

  @protected
  EditorView sse_decode_editor_view(SseDeserializer deserializer);

  @protected
  ExtraFile sse_decode_extra_file(SseDeserializer deserializer);

  @protected
  HighlightSpan sse_decode_highlight_span(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ExtraFile> sse_decode_list_extra_file(SseDeserializer deserializer);

  @protected
  List<HighlightSpan> sse_decode_list_highlight_span(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RenderLine> sse_decode_list_render_line(SseDeserializer deserializer);

  @protected
  List<TypstError> sse_decode_list_typst_error(SseDeserializer deserializer);

  @protected
  List<TypstPage> sse_decode_list_typst_page(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VimAction? sse_decode_opt_box_autoadd_vim_action(
    SseDeserializer deserializer,
  );

  @protected
  VimRange? sse_decode_opt_box_autoadd_vim_range(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  RenderLine sse_decode_render_line(SseDeserializer deserializer);

  @protected
  TypstCompileResult sse_decode_typst_compile_result(
    SseDeserializer deserializer,
  );

  @protected
  TypstError sse_decode_typst_error(SseDeserializer deserializer);

  @protected
  TypstPage sse_decode_typst_page(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VimAction sse_decode_vim_action(SseDeserializer deserializer);

  @protected
  VimMode sse_decode_vim_mode(SseDeserializer deserializer);

  @protected
  VimRange sse_decode_vim_range(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vim_action(
    VimAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vim_range(
    VimRange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_editor_view(EditorView self, SseSerializer serializer);

  @protected
  void sse_encode_extra_file(ExtraFile self, SseSerializer serializer);

  @protected
  void sse_encode_highlight_span(HighlightSpan self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_extra_file(
    List<ExtraFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_highlight_span(
    List<HighlightSpan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_render_line(
    List<RenderLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_typst_error(
    List<TypstError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_typst_page(
    List<TypstPage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_vim_action(
    VimAction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_vim_range(
    VimRange? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_line(RenderLine self, SseSerializer serializer);

  @protected
  void sse_encode_typst_compile_result(
    TypstCompileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_typst_error(TypstError self, SseSerializer serializer);

  @protected
  void sse_encode_typst_page(TypstPage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vim_action(VimAction self, SseSerializer serializer);

  @protected
  void sse_encode_vim_mode(VimMode self, SseSerializer serializer);

  @protected
  void sse_encode_vim_range(VimRange self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
