// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'editor.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'highlighter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vim_engine.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -208112774;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'typink_rust',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List?> crateApiCompilePdf({
    required String content,
    required List<ExtraFile> extraFiles,
  });

  Future<TypstCompileResult> crateApiCompileTypst({
    required String content,
    required List<ExtraFile> extraFiles,
  });

  String crateApiGetEditorContent();

  EditorView crateApiGetEditorView({
    required BigInt startLine,
    required BigInt endLine,
  });

  VimAction? crateApiHandleEditorKey({required String key});

  void crateApiHandleEditorReplaceRange({
    required BigInt startU16,
    required BigInt endU16,
    required String text,
    BigInt? cursorU16,
  });

  Future<void> crateApiHandleEditorTriggerHighlight();

  void crateApiHandleEditorUpdateSelection({required BigInt cursorU16});

  Future<String> crateApiHelloFromRust();

  void crateApiSetEditorContent({required String content});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List?> crateApiCompilePdf({
    required String content,
    required List<ExtraFile> extraFiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          sse_encode_list_extra_file(extraFiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCompilePdfConstMeta,
        argValues: [content, extraFiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompilePdfConstMeta => const TaskConstMeta(
    debugName: "compile_pdf",
    argNames: ["content", "extraFiles"],
  );

  @override
  Future<TypstCompileResult> crateApiCompileTypst({
    required String content,
    required List<ExtraFile> extraFiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          sse_encode_list_extra_file(extraFiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_typst_compile_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCompileTypstConstMeta,
        argValues: [content, extraFiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompileTypstConstMeta => const TaskConstMeta(
    debugName: "compile_typst",
    argNames: ["content", "extraFiles"],
  );

  @override
  String crateApiGetEditorContent() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetEditorContentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetEditorContentConstMeta =>
      const TaskConstMeta(debugName: "get_editor_content", argNames: []);

  @override
  EditorView crateApiGetEditorView({
    required BigInt startLine,
    required BigInt endLine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(startLine, serializer);
          sse_encode_usize(endLine, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_editor_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetEditorViewConstMeta,
        argValues: [startLine, endLine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetEditorViewConstMeta => const TaskConstMeta(
    debugName: "get_editor_view",
    argNames: ["startLine", "endLine"],
  );

  @override
  VimAction? crateApiHandleEditorKey({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_vim_action,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHandleEditorKeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandleEditorKeyConstMeta =>
      const TaskConstMeta(debugName: "handle_editor_key", argNames: ["key"]);

  @override
  void crateApiHandleEditorReplaceRange({
    required BigInt startU16,
    required BigInt endU16,
    required String text,
    BigInt? cursorU16,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(startU16, serializer);
          sse_encode_usize(endU16, serializer);
          sse_encode_String(text, serializer);
          sse_encode_opt_box_autoadd_usize(cursorU16, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHandleEditorReplaceRangeConstMeta,
        argValues: [startU16, endU16, text, cursorU16],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandleEditorReplaceRangeConstMeta =>
      const TaskConstMeta(
        debugName: "handle_editor_replace_range",
        argNames: ["startU16", "endU16", "text", "cursorU16"],
      );

  @override
  Future<void> crateApiHandleEditorTriggerHighlight() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHandleEditorTriggerHighlightConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandleEditorTriggerHighlightConstMeta =>
      const TaskConstMeta(
        debugName: "handle_editor_trigger_highlight",
        argNames: [],
      );

  @override
  void crateApiHandleEditorUpdateSelection({required BigInt cursorU16}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(cursorU16, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHandleEditorUpdateSelectionConstMeta,
        argValues: [cursorU16],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandleEditorUpdateSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "handle_editor_update_selection",
        argNames: ["cursorU16"],
      );

  @override
  Future<String> crateApiHelloFromRust() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHelloFromRustConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHelloFromRustConstMeta =>
      const TaskConstMeta(debugName: "hello_from_rust", argNames: []);

  @override
  void crateApiSetEditorContent({required String content}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetEditorContentConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetEditorContentConstMeta => const TaskConstMeta(
    debugName: "set_editor_content",
    argNames: ["content"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  VimAction dco_decode_box_autoadd_vim_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vim_action(raw);
  }

  @protected
  VimRange dco_decode_box_autoadd_vim_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vim_range(raw);
  }

  @protected
  EditorView dco_decode_editor_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EditorView(
      lines: dco_decode_list_render_line(arr[0]),
      cursorLine: dco_decode_usize(arr[1]),
      cursorColumnU16: dco_decode_usize(arr[2]),
      cursorGlobalU16: dco_decode_usize(arr[3]),
      mode: dco_decode_vim_mode(arr[4]),
    );
  }

  @protected
  ExtraFile dco_decode_extra_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExtraFile(
      name: dco_decode_String(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  HighlightSpan dco_decode_highlight_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HighlightSpan(
      start: dco_decode_usize(arr[0]),
      end: dco_decode_usize(arr[1]),
      label: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ExtraFile> dco_decode_list_extra_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_extra_file).toList();
  }

  @protected
  List<HighlightSpan> dco_decode_list_highlight_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_highlight_span).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RenderLine> dco_decode_list_render_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_render_line).toList();
  }

  @protected
  List<TypstError> dco_decode_list_typst_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_typst_error).toList();
  }

  @protected
  List<TypstPage> dco_decode_list_typst_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_typst_page).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  VimAction? dco_decode_opt_box_autoadd_vim_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_vim_action(raw);
  }

  @protected
  VimRange? dco_decode_opt_box_autoadd_vim_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_vim_range(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  RenderLine dco_decode_render_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RenderLine(
      text: dco_decode_String(arr[0]),
      spans: dco_decode_list_highlight_span(arr[1]),
      isComposing: dco_decode_bool(arr[2]),
      startU16: dco_decode_usize(arr[3]),
    );
  }

  @protected
  TypstCompileResult dco_decode_typst_compile_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TypstCompileResult(
      pages: dco_decode_list_typst_page(arr[0]),
      errors: dco_decode_list_typst_error(arr[1]),
    );
  }

  @protected
  TypstError dco_decode_typst_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TypstError(
      message: dco_decode_String(arr[0]),
      line: dco_decode_u_32(arr[1]),
      column: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  TypstPage dco_decode_typst_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return TypstPage(image: dco_decode_list_prim_u_8_strict(arr[0]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VimAction dco_decode_vim_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VimAction(
      mode: dco_decode_vim_mode(arr[0]),
      cursorLine: dco_decode_usize(arr[1]),
      cursorColumn: dco_decode_usize(arr[2]),
      selectionStartLine: dco_decode_opt_box_autoadd_usize(arr[3]),
      selectionStartColumn: dco_decode_opt_box_autoadd_usize(arr[4]),
      deleteRange: dco_decode_opt_box_autoadd_vim_range(arr[5]),
      insertText: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  VimMode dco_decode_vim_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VimMode.values[raw as int];
  }

  @protected
  VimRange dco_decode_vim_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VimRange(
      startLine: dco_decode_usize(arr[0]),
      startColumn: dco_decode_usize(arr[1]),
      endLine: dco_decode_usize(arr[2]),
      endColumn: dco_decode_usize(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  VimAction sse_decode_box_autoadd_vim_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vim_action(deserializer));
  }

  @protected
  VimRange sse_decode_box_autoadd_vim_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vim_range(deserializer));
  }

  @protected
  EditorView sse_decode_editor_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_render_line(deserializer);
    var var_cursorLine = sse_decode_usize(deserializer);
    var var_cursorColumnU16 = sse_decode_usize(deserializer);
    var var_cursorGlobalU16 = sse_decode_usize(deserializer);
    var var_mode = sse_decode_vim_mode(deserializer);
    return EditorView(
      lines: var_lines,
      cursorLine: var_cursorLine,
      cursorColumnU16: var_cursorColumnU16,
      cursorGlobalU16: var_cursorGlobalU16,
      mode: var_mode,
    );
  }

  @protected
  ExtraFile sse_decode_extra_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return ExtraFile(name: var_name, data: var_data);
  }

  @protected
  HighlightSpan sse_decode_highlight_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_usize(deserializer);
    var var_end = sse_decode_usize(deserializer);
    var var_label = sse_decode_String(deserializer);
    return HighlightSpan(start: var_start, end: var_end, label: var_label);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ExtraFile> sse_decode_list_extra_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExtraFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_extra_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<HighlightSpan> sse_decode_list_highlight_span(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HighlightSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_highlight_span(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RenderLine> sse_decode_list_render_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RenderLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_render_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<TypstError> sse_decode_list_typst_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TypstError>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_typst_error(deserializer));
    }
    return ans_;
  }

  @protected
  List<TypstPage> sse_decode_list_typst_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TypstPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_typst_page(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VimAction? sse_decode_opt_box_autoadd_vim_action(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_vim_action(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VimRange? sse_decode_opt_box_autoadd_vim_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_vim_range(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RenderLine sse_decode_render_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_spans = sse_decode_list_highlight_span(deserializer);
    var var_isComposing = sse_decode_bool(deserializer);
    var var_startU16 = sse_decode_usize(deserializer);
    return RenderLine(
      text: var_text,
      spans: var_spans,
      isComposing: var_isComposing,
      startU16: var_startU16,
    );
  }

  @protected
  TypstCompileResult sse_decode_typst_compile_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pages = sse_decode_list_typst_page(deserializer);
    var var_errors = sse_decode_list_typst_error(deserializer);
    return TypstCompileResult(pages: var_pages, errors: var_errors);
  }

  @protected
  TypstError sse_decode_typst_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    var var_line = sse_decode_u_32(deserializer);
    var var_column = sse_decode_u_32(deserializer);
    return TypstError(message: var_message, line: var_line, column: var_column);
  }

  @protected
  TypstPage sse_decode_typst_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_image = sse_decode_list_prim_u_8_strict(deserializer);
    return TypstPage(image: var_image);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VimAction sse_decode_vim_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_vim_mode(deserializer);
    var var_cursorLine = sse_decode_usize(deserializer);
    var var_cursorColumn = sse_decode_usize(deserializer);
    var var_selectionStartLine = sse_decode_opt_box_autoadd_usize(deserializer);
    var var_selectionStartColumn = sse_decode_opt_box_autoadd_usize(
      deserializer,
    );
    var var_deleteRange = sse_decode_opt_box_autoadd_vim_range(deserializer);
    var var_insertText = sse_decode_opt_String(deserializer);
    return VimAction(
      mode: var_mode,
      cursorLine: var_cursorLine,
      cursorColumn: var_cursorColumn,
      selectionStartLine: var_selectionStartLine,
      selectionStartColumn: var_selectionStartColumn,
      deleteRange: var_deleteRange,
      insertText: var_insertText,
    );
  }

  @protected
  VimMode sse_decode_vim_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VimMode.values[inner];
  }

  @protected
  VimRange sse_decode_vim_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_usize(deserializer);
    var var_startColumn = sse_decode_usize(deserializer);
    var var_endLine = sse_decode_usize(deserializer);
    var var_endColumn = sse_decode_usize(deserializer);
    return VimRange(
      startLine: var_startLine,
      startColumn: var_startColumn,
      endLine: var_endLine,
      endColumn: var_endColumn,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vim_action(
    VimAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vim_action(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vim_range(
    VimRange self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vim_range(self, serializer);
  }

  @protected
  void sse_encode_editor_view(EditorView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_render_line(self.lines, serializer);
    sse_encode_usize(self.cursorLine, serializer);
    sse_encode_usize(self.cursorColumnU16, serializer);
    sse_encode_usize(self.cursorGlobalU16, serializer);
    sse_encode_vim_mode(self.mode, serializer);
  }

  @protected
  void sse_encode_extra_file(ExtraFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_highlight_span(HighlightSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.start, serializer);
    sse_encode_usize(self.end, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_extra_file(
    List<ExtraFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_extra_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_highlight_span(
    List<HighlightSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_highlight_span(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_render_line(
    List<RenderLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_render_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_typst_error(
    List<TypstError> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_typst_error(item, serializer);
    }
  }

  @protected
  void sse_encode_list_typst_page(
    List<TypstPage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_typst_page(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_vim_action(
    VimAction? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_vim_action(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_vim_range(
    VimRange? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_vim_range(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_render_line(RenderLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_list_highlight_span(self.spans, serializer);
    sse_encode_bool(self.isComposing, serializer);
    sse_encode_usize(self.startU16, serializer);
  }

  @protected
  void sse_encode_typst_compile_result(
    TypstCompileResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_typst_page(self.pages, serializer);
    sse_encode_list_typst_error(self.errors, serializer);
  }

  @protected
  void sse_encode_typst_error(TypstError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
    sse_encode_u_32(self.line, serializer);
    sse_encode_u_32(self.column, serializer);
  }

  @protected
  void sse_encode_typst_page(TypstPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.image, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vim_action(VimAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vim_mode(self.mode, serializer);
    sse_encode_usize(self.cursorLine, serializer);
    sse_encode_usize(self.cursorColumn, serializer);
    sse_encode_opt_box_autoadd_usize(self.selectionStartLine, serializer);
    sse_encode_opt_box_autoadd_usize(self.selectionStartColumn, serializer);
    sse_encode_opt_box_autoadd_vim_range(self.deleteRange, serializer);
    sse_encode_opt_String(self.insertText, serializer);
  }

  @protected
  void sse_encode_vim_mode(VimMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_vim_range(VimRange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.startLine, serializer);
    sse_encode_usize(self.startColumn, serializer);
    sse_encode_usize(self.endLine, serializer);
    sse_encode_usize(self.endColumn, serializer);
  }
}
