// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HighlightSpan {
  final BigInt start;
  final BigInt end;
  final String label;
  final bool bold;
  final bool italic;
  final int? headingLevel;

  const HighlightSpan({
    required this.start,
    required this.end,
    required this.label,
    required this.bold,
    required this.italic,
    this.headingLevel,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      label.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      headingLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          label == other.label &&
          bold == other.bold &&
          italic == other.italic &&
          headingLevel == other.headingLevel;
}
