// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VimAction {
  final VimMode mode;
  final BigInt cursorLine;
  final BigInt cursorColumn;
  final BigInt? selectionStartLine;
  final BigInt? selectionStartColumn;
  final VimRange? deleteRange;
  final String? insertText;
  final String? commandText;
  final List<String>? replayKeys;
  final String? signal;
  final String? yankText;

  const VimAction({
    required this.mode,
    required this.cursorLine,
    required this.cursorColumn,
    this.selectionStartLine,
    this.selectionStartColumn,
    this.deleteRange,
    this.insertText,
    this.commandText,
    this.replayKeys,
    this.signal,
    this.yankText,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      cursorLine.hashCode ^
      cursorColumn.hashCode ^
      selectionStartLine.hashCode ^
      selectionStartColumn.hashCode ^
      deleteRange.hashCode ^
      insertText.hashCode ^
      commandText.hashCode ^
      replayKeys.hashCode ^
      signal.hashCode ^
      yankText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VimAction &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          cursorLine == other.cursorLine &&
          cursorColumn == other.cursorColumn &&
          selectionStartLine == other.selectionStartLine &&
          selectionStartColumn == other.selectionStartColumn &&
          deleteRange == other.deleteRange &&
          insertText == other.insertText &&
          commandText == other.commandText &&
          replayKeys == other.replayKeys &&
          signal == other.signal &&
          yankText == other.yankText;
}

enum VimMode {
  normal,
  insert,
  visual,
  visualLine,
  search,
  command,
  visualBlock,
  replace,
  ;
}

class VimRange {
  final BigInt startLine;
  final BigInt startColumn;
  final BigInt endLine;
  final BigInt endColumn;

  const VimRange({
    required this.startLine,
    required this.startColumn,
    required this.endLine,
    required this.endColumn,
  });

  @override
  int get hashCode =>
      startLine.hashCode ^
      startColumn.hashCode ^
      endLine.hashCode ^
      endColumn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VimRange &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          startColumn == other.startColumn &&
          endLine == other.endLine &&
          endColumn == other.endColumn;
}
